### PR TITLE
Refactor Components

### LINKED ISSUE #13: Migrate away from the deprecated Plugin Components
According to [Plugin Components](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_components.html), these are the legacy extension points and should be avoided. They are actively used by this plugin, however. It would be great to keep up to date with the IntelliJ platform so that the plugin does not affect the performance of the IDEA and does not break in the future.

### PR DESCRIPTION
**Pull request by duemir**
This builds on top of #4 and attempts to resolve #13.

The components were used to imperatively add extensions. All the same, extension should now be registered declaratively via the `plugin.xml`

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Thank you for this contribution! It is much appreciated.

Are you doing it as a part of the [Jenkins UI/UX Hackfest](https://www.jenkins.io/events/online-hackfest/2020-uiux/)? If so, please consider reporting this contribution [here](https://github.com/jenkinsci/ui-ux-hackfest-2020/issues/new/choose) so that we could facilitate reviews and share the story 👍

**Comment by duemir** [comment]
For anybody who wants to test [idea-stapler-plugin-1.8.zip](https://github.com/stapler/idea-stapler-plugin/files/5222691/idea-stapler-plugin-1.8.zip)

**Comment by timja** [comment]
@duemir I can't seem to click through on any tags any more.

image

**Comment by duemir** [comment]
Thank you for trying @timja . That's a major regression. I will check.

**Comment by duemir** [comment]
@timja do you have red warning sign in bottom right? When clicked, does it complane about Stapler Framework plugin throwing following?

```
java.lang.NoClassDefFoundError: com/intellij/psi/JavaPsiFacade
	at org.kohsuke.stapler.idea.descriptor.XmlNSDescriptorImpl.get(XmlNSDescriptorImpl.java:135)
	at org.kohsuke.stapler.idea.descriptor.XmlSchemaProviderImpl.getSchema(XmlSchemaProviderImpl.java:25)
	at com.intellij.xml.XmlSchemaProvider.findSchema(XmlSchemaProvider.java:39)
	at com.intellij.xml.XmlSchemaProvider.findSchema(XmlSchemaProvider.java:51)
	at com.intellij.javaee.ExternalResourceManagerExImpl.getResourceLocation(ExternalResourceManagerExImpl.java:224)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.retrieveFile(XmlTagDelegate.java:415)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.lambda$initializeSchema$2(XmlTagDelegate.java:323)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:2078)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.lambda$initializeSchema$4(XmlTagDelegate.java:323)
	at com.intellij.openapi.util.NullableLazyValue$1.compute(NullableLazyValue.java:52)
	at com.intellij.openapi.util.NullableLazyValue.getValue(NullableLazyValue.java:36)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getNSDescriptor(XmlTagDelegate.java:220)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getNSDescriptor(XmlTagImpl.java:100)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:479)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:437)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:433)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:129)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptionImpl(XmlAttributeDelegate.java:64)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.lambda$getDescriptor$0(XmlAttributeDelegate.java:53)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptor(XmlAttributeDelegate.java:51)
	at com.intellij.psi.impl.source.xml.XmlAttributeImpl.getDescriptor(XmlAttributeImpl.java:207)
	at com.intellij.xml.util.XmlPrefixReferenceProvider.getReferencesByElement(XmlPrefixReferenceProvider.java:48)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:202)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:145)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:44)
	at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:89)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:57)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:51)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.findReferenceAt(CompositePsiElement.java:118)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:240)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:225)
	at com.intellij.codeInsight.daemon.impl.quickfix.BaseExtResourceAction.findUri(BaseExtResourceAction.java:65)
	at com.intellij.codeInsight.daemon.impl.quickfix.BaseExtResourceAction.isAvailable(BaseExtResourceAction.java:23)
	at com.intellij.codeInsight.daemon.impl.quickfix.ManuallySetupExtResourceAction.isAvailable(ManuallySetupExtResourceAction.java:12)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:322)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:190)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:321)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:281)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:255)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$calcIntentions$1(ShowIntentionActionsHandler.java:113)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:855)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$underModalProgress$0(ActionUtil.java:224)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$underModalProgress$1(ActionUtil.java:225)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by timja** [comment]
No I don't I re-installed the plugin to test it and this time it looks slightly different:

image

click through doesn't work still

the taglib namespaces can't be resolved

**Comment by timja** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004978640-java-lang-NoClassDefFoundError-in-test-after-upgrading-on-2019-2

**Comment by duemir** [comment]
Yep, Java dependency needs to be explicitly defined.

**Comment by duemir** [comment]
Rebased on top of the current master. Although, It is still not functional since the 'java" plugin dependency is not yet explicitly added.

**Comment by duemir** [comment]
Merging #37 should unblock this.

**Comment by duemir** [comment]
[idea-stapler-plugin-1.9.0.zip](https://github.com/stapler/idea-stapler-plugin/files/6098992/idea-stapler-plugin-1.9.0.zip) should be working on the latest release now. This should be good for testing now.

**Comment by timja** [comment]
After using it for a few minutes I can't see any errors

**Comment by duemir** [comment]
While rebasing has not noticed the duplication of two `depends` statements. Removed them now. Functionally it didn't seem to have any adverse effect. None of them are optional with conditional extensions associated with them.
Here is a new build for this new commit: [idea-stapler-plugin-1.9.0+07e67609c6b.zip](https://github.com/stapler/idea-stapler-plugin/files/6120406/idea-stapler-plugin-1.9.0%2B07e67609c6b.zip)

**Comment by duemir** [comment]
Hey @oleg-nenashev @daniel-beck What do you think?

**Review by oleg-nenashev — APPROVED** [review]
no objections from me as long as the changes work. I have not tested it locally though.
Having a renovated plugin for IDEA would be awesome

**Pull request merged**
