### PR TITLE
Enable the Release Drafter based on jenkinsci documentation

### LINKED ISSUE #19: Automate changelogs with Release Drafter
Release Drafter could be a handy tool, and developers would benefit from changelogs. https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

### PR DESCRIPTION
**Pull request by duemir**
Resolve #19 by following the https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
You can inherit configs instead of copying them. Copying is a right thing to do if you plan major changes later

**Comment by duemir** [comment]
@oleg-nenashev, are you referring to `_extends:`? I haven't seen it mentioned in the [upstream documentation](https://github.com/release-drafter/release-drafter), so wasn't sure how it works and if it works across organizations

**Comment by oleg-nenashev** [comment]
Yes, it works. Example:
https://github.com/jenkins-infra/plugin-site/blob/master/.github/release-drafter.yml

**Comment by duemir** [comment]
Thanks for pointing that out. I adopted the `_extends`

**Review by oleg-nenashev — APPROVED** [review]

**Pull request merged**
